### ISSUE TITLE
Плагин начал вылетать в ошибку

### ISSUE THREAD

**Issue by Sheredeka** [Nemiroff/plugin.audio.radiorecord#1]
Собственно лог:

2020-02-20 11:15:58.333 T:3304784768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'simplejson.errors.JSONDecodeError'>
                                            Error Contents: Expecting value: line 1 column 1 (char 0)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.radiorecord/addon.py", line 13, in <module>
                                                station_list = requests.get("https://www.radiorecord.ru/radioapi/stations/").json()
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 897, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/usr/lib/python2.7/site-packages/simplejson/__init__.py", line 518, in loads
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
                                              File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
                                              File "/usr/lib/python2.7/site-packages/simplejson/scanner.py", line 79, in scan_once
                                              File "/usr/lib/python2.7/site-packages/simplejson/scanner.py", line 70, in _scan_once
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                            -->End of Python script error report<--
2020-02-20 11:15:58.587 T:3262858112   ERROR: GetDirectory - Error getting plugin://plugin.audio.radiorecord/
2020-02-20 11:15:58.600 T:4087306064   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.radiorecord/) failed

**Comment by Nemiroff** [comment]
Какая то проблема с API. Android приложение тоже не работает.

**Comment by Nemiroff** [comment]
Вроде починили API.
